### ISSUE TITLE
!($(ILRepackMergeDebugSymbols))

### ISSUE THREAD

**Issue by TomLiu-GitHub** [kekyo/ILRepack.FullAuto#1]
!($(ILRepackMergeDebugSymbols))”中，“$(ILRepackMergeDebugSymbols)”的计算结果应为布尔值而不是“”

**Comment by kekyo** [comment]
Are you referring to a situation where the `DebugSymbols` variable is not explicitly specified in the project?
This package referring `DebugSymbols` variable when does not explicitly declare `ILRepackMergeDebugSymbols`.

**Comment by TomLiu-GitHub** [comment]
thinks
