### ISSUE TITLE
Cannot build due to $(_IlRepack_IsTargetCinfiguration) returing ""

### ISSUE THREAD

**Issue by SkierJa** [kekyo/ILRepack.FullAuto#11]
All I did is adding <ILRepackTargetConfigurations>Debug;Release</ILRepackTargetConfigurations> to the first PropertyGroup in ILRepack.FullAuto.targets. It doesn't work even after reverting the change.

"$(_ILRepack_IsTargetConfiguration)" element was expected to be evaluated as a boolean value, but instead was "". In condition "$(ILRepackBuildEnable) AND $(_ILRepack_IsTargetConfiguration)".  C:\Users\xxx\Desktop\git repo\MyApp\packages\ILRepack.FullAuto.1.5.0\build\ILRepack.FullAuto.targets

**Comment by SkierJa** [comment]
https://github.com/kekyo/ILRepack.FullAuto/issues/10#issuecomment-1955233724
I changed Target Name as mentioned in the quote above and it seems to work but now I have a problem with HelixToolKit.WPF.SharpDX, on Run the debugger throws that it cannot find it?

**Comment by kekyo** [comment]
Hi,

> I have a problem with HelixToolKit.WPF.SharpDX

I am not sure what is going on with this issue. The former problem with `$(_ILRepack_IsTargetConfiguration)` not being evaluated, maybe you are manually importing only the `ILRepack.FullAuto.targets` script?

I have a feeling that `_ILRepack_IsTargetConfiguration` is used for both MSBuild custom tasks and variables, and that if the `ILRepack.FullAuto.props` script is not imported beforehand, the problematic situation may occur (Untested. However, I believe I made a mistake using the same symbol name and may correct it).

If I am not mistaken about the issue, I believe that these scripts will work correctly when introduced as a NuGet package, as they are automatically referenced.

**Comment by kekyo** [comment]
It will be closed, so if you have any problems, please reopen it.
