### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by ambyte** [kekyo/ILRepack.FullAuto#15]
NET Framework 4.7.2

Installed the latest version of the package 1.6.0

After build I get an error

Expected "$(_ILRepack_IsTargetConfiguration)" to evaluate to a boolean instead of "", in condition "$(ILRepackBuildEnable) AND $(_ILRepack_IsTargetConfiguration)".  C:\Users\user\.nuget\packages\ilrepack.fullauto\1.6.0\build\ILRepack.FullAuto.targets

**Comment by kekyo** [comment]
Hmm, there are no problems in my environment, but there have been similar reports in the past, so I'll try to fix it.

**Comment by ambyte** [comment]
My project file was in the old format, I updated it to the new SDK format and it started working

**Comment by kekyo** [comment]
Oh, that might be the cause! In any case, I'll fix it for the next release. Thanks!
