### ISSUE TITLE
"$(ILRepackMergeDebugSymbols)" evaluates to "" instead of a boolean

### ISSUE THREAD

**Issue by runembp** [kekyo/ILRepack.FullAuto#3]
Hi there, 

I stumbled upon your git and tried it out. Unfortunately, it doesn't seem your v.1.1.0 release fixed the issue of ILRepackMergeDebugSymbols evaluation.

![image](https://user-images.githubusercontent.com/58623004/204775595-a6a6c3b2-2609-43a1-911f-a867042d91d8.png)

I was using Jetbrains Rider on a simple Dynamics CRM plugin (C# Library) in a .Net Framework 4.7.2 project. Not sure what other you might need. :-)

**Comment by kekyo** [comment]
@runembp Sorry later, will check soon!

**Comment by kekyo** [comment]
I found a bug: https://github.com/kekyo/ILRepack.FullAuto/blob/a71291803d2b6759e687d9719b033de655a3db7a/ILRepack.FullAuto/build/ILRepack.FullAuto.targets#L93

It uses `ILRepackMergeDebugSymbols` instead of `_ILRepack_MergeDebugSymbols`...

Will fix and release.

**Comment by kekyo** [comment]
@runembp 1.2.0 is being deployed. Could you test it?
