### ISSUE TITLE
InvalidCastException when trying to merge Oracle.ManagedDataAccess.dll

### ISSUE THREAD

**Issue by javeiga-iest** [kekyo/ILRepack.FullAuto#5]
1>  System.InvalidCastException: No se puede convertir un objeto de tipo 'System.SByte' al tipo 'System.String'.
1>     en Mono.Cecil.MetadataBuilder.GetConstantSignature(ElementType type, Object value)
1>     en Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
1>     en Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
1>     en Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
1>     en Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>     en Mono.Cecil.MetadataBuilder.AddTypeDefs()
1>     en Mono.Cecil.MetadataBuilder.BuildTypes()
1>     en Mono.Cecil.MetadataBuilder.BuildModule()
1>     en Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>     en Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
1>     en Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>     en ILRepacking.ILRepack.Repack()
1>     en ILRepacking.Application.Main(String[] args)
This works fine if we use the Oracle.ManagedDataAccess.dll v 19.18.0. All versions after that one returns System.InvalidCastException.

Any idea how to fix it?

**Comment by kekyo** [comment]
@javeiga-iest Thank you for using ILRepack.FullAuto!

Looking at this stack frame, perhaps it is an error emitted by the original ILRepack, I have no idea what caused it.
(ILRepack.FullAuto internally uses the ILRepack package binary as-is to build)

Perhaps asking in the ILRepack repository might shed some light...

**Comment by kekyo** [comment]
It looks like there will probably be no additional information, so I will close it once. If there are any problems, please reopen.
