### ISSUE TITLE
Failed to load assembly

### ISSUE THREAD

**Issue by wally96334** [kekyo/ILRepack.FullAuto#6]
Hi,

I am developing a WPF app with Visual Studio 2017 Community on a Win 10 Pro system. It builds successfully for release without ILRepack.

When I build the project with ILRepack/ILRepack.Auto, I get the following error.
(I have cleaned this up as best as I can from the jumble that was in the output window to hopefully make this easier to comprehend.)

Please note that the library "ScintillaNET.WPF.dll" is built for x86. Could that be causing the problem?

=========================================

Severity    Code    Description Project File    Line    Suppression State

Error       The command ""C:\Projects\Project_12\Solution_folder\packages\ILRepack.2.0.18\tools\ILRepack.exe"
--parallel --union  --internalize --allowduplicateresources
--lib:"

C:\Projects\Project_12\SCIde.WPF.NTF_SCide_file_ref\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\Microsoft.Net.Http.2.2.29\lib\net45;
C:\Projects\Project_12\Solution_folder\packages\System.Memory.4.5.5\lib\net461;
C:\Projects\Project_12\KwKK_N__Log_LIB_01\bin\Release;
C:\Projects\Project_12\ScintillaNET.WPF-master_01\SCide.WPF\bin\x86\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Buffers.4.5.1\lib\net461;
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7;
C:\Projects\Project_12\Solution_folder\Libraries;
C:\Projects\Project_12\ScintillaNET.WPF-master_01\ScintillaNET.WPF\bin\x86\Release;
C:\Projects\Project_12\Solution_folder\packages\Expression.Blend.Sdk.1.0.2\lib\net45;
C:\Projects\Project_12\Solution_folder\packages\System.Runtime.4.3.1\lib\net462;
C:\Projects\Project_12\Solution_folder\packages\System.Security.Cryptography.X509Certificates.4.3.0\lib\net461;
C:\Projects\Project_12\JSON_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Net.Http.4.3.4\lib\net46;
C:\Projects\Project_12\Solution_folder\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Runtime.CompilerServices.Unsafe.6.0.0\lib\net461;
C:\Projects\Project_12\File_Selection_Popup_KwK_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\OpenDialog.1.1.1\lib\net45;
C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.5\Libraries;
C:\Projects\Project_12\Dynamic_Tab_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\WindowsAPICodePack-ShellExtensions.1.1.1\lib;
C:\Rosyln_01\CSI_01\CSI_eval_LIB_01\bin\Release;
C:\Projects\Project_12\WPF_Controls_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\NLog.4.3.7\lib\net45;
C:\Projects\Project_12\KwK_Exception_01\bin\Release;
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7\Facades;
C:\Projects\Project_12\Solution_folder\packages\System.Formats.Asn1.7.0.0\lib\net462;
C:\Projects\Project_12\Solution_folder\packages\WindowsAPICodePack-Core.1.1.2\lib;
C:\Projects\Project_12\SCIde.WPF.NTF_tab_name_index_ref_LIB_01\bin\Release;
C:\DOT_NET\Utility\Utility_WPF_LIB_01\Utility_NET_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Security.Cryptography.Algorithms.4.3.0\lib\net461;
C:\DOT_NET\Utility\Utility_LIB_02\LIB_Utility_02\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Data.Common.4.3.0\lib\net451;
C:\Projects\Project_12\File_Selection_KwK_LIB_01\bin\Release;
C:\Projects\Project_12\ScintillaNET.WPF-master_01\SCide.WPF.Exception_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\System.Security.Cryptography.Primitives.4.3.0\lib\net46;
C:\Projects\Project_12\Solution_folder\packages\gong-wpf-dragdrop.1.1.0\lib\net40;
C:\File_IO_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\JSON_LIB_02\bin\Release;
C:\Projects\Project_12\Utility_LIB_01\bin\Release;
C:\Projects\Project_12\Solution_folder\packages\WindowsAPICodePack-Shell.1.1.1\lib;
C:\Projects\Project_12\Solution_folder\packages\System.Threading.Tasks.Extensions.4.5.4\lib\net461;
C:\Projects\Project_12\Solution_folder\packages\System.Security.Cryptography.Encoding.4.3.0\lib\net46;
C:\Projects\Project_12\Solution_folder\packages\System.Numerics.Vectors.4.5.0\lib\net46"

--noRepackRes
--out:"C:\Projects\Project_12\Solution_folder\obj\x86\Release\Executable_01.exe"

"C:\Projects\Project_12\Solution_folder\obj\x86\Release\Executable_01.exe"
"C:\Projects\Project_12\Solution_folder\bin\Release\BouncyCastle.Cryptography.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\CSI_eval_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Dir_Operations_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Dynamic_Tab_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\File_IO_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\File_Selection_KwK_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\File_Selection_Popup_KwK_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Gat.Controls.OpenDialog.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\GongSolutions.Wpf.DragDrop.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\HtmlAgilityPack.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\index_for_JScript_NET_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\IronPython.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\JSON_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\JSON_LIB_02.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\JSON_MGMT_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\KwiKKalK_js_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\KwKK_N__Log_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\KwK_Exception_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\KwK_Exception_Helper_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\LIB_Utility_02.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Logging_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\MailKit.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.CodeAnalysis.CSharp.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.CodeAnalysis.CSharp.Scripting.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.CodeAnalysis.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.CodeAnalysis.Scripting.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Dynamic.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Expression.Drawing.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Expression.Effects.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Expression.Interactions.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Scripting.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.Scripting.Metadata.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.WindowsAPICodePack.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.WindowsAPICodePack.Shell.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Microsoft.WindowsAPICodePack.ShellExtensions.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\MimeKit.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\netstandard.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Newtonsoft.Json.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\NLog.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Node_JS_Server_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\N__LOG_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\OpenPop.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Pipe.Net.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\SCide.WPF.Exception_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\SCIde.WPF.NTF_SCide_file_ref.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\SCIde.WPF.NTF_tab_name_index_ref_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\ScintillaNET FindReplaceDialog.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\ScintillaNET.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\ScintillaNET.WPF.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Buffers.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Data.Common.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Formats.Asn1.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Management.Automation.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Memory.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Net.Http.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Net.Http.Extensions.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Net.Http.Primitives.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Numerics.Vectors.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Runtime.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Security.Cryptography.Algorithms.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Security.Cryptography.Encoding.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Security.Cryptography.Primitives.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Security.Cryptography.X509Certificates.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Threading.Tasks.Extensions.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\System.Windows.Interactivity.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Threading_Utiity_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Utility_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Utility_NET_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\WCF_Duplex_Pipe_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\WCF_Pipe_Client_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\WCF_PP_Pipe_exception_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\WPF_Controls_LIB_01.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Xceed.Wpf.AvalonDock.dll"
"C:\Projects\Project_12\Solution_folder\bin\Release\Xceed.Wpf.AvalonDock.Themes.VS2010.dll""

exited with code 1.  

Primary_Calc_Console_01         

Error       Failed to load assembly

C:\Projects\Project_12\Solution_folder\bin\Release\ScintillaNET.WPF.dll
 Console_01

C:\Projects\Project_12\Solution_folder\EXEC     

=========================================

Any assistance with this would be appreciated.

THANKS!

**Comment by kekyo** [comment]
Thanks reached out!

Looking at the logs, it seems that ILRepack is silently returning an error code and failing.
Unfortunately I don't know the cause either, since ILRepack.FullAuto is using the official ILRepack as is.

I suggest you try to manually run the command issuing part `Error The command "` in the log and see what happens. If this gives the same error, it may contain a problem that ILRepack cannot handle, or it may be a problem with ILRepack itself.
If it succeeds when you run it manually, the problem may be on the ILRepack.FullAuto side.

**Comment by kekyo** [comment]
In 1.3.0, ILRepack has not been upgraded in a while and 2.0.22 has been released to follow. I do not know the cause of this problem, but maybe it will fix the problem. I suggest you try it and see.

Related #7
