### ISSUE TITLE
Package depends on mono on non-Windows OS

### ISSUE THREAD

**Issue by Tejes** [kekyo/ILRepack.FullAuto#9]
Running on Ubuntu 23.10, .NET SDK 7.0, referenced the 1.5.0 version of the package, no other configuration added. Build output:

```
$ dotnet pack -c Release
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  /usr/bin/sh: 2: /tmp/MSBuildTempuser/tmpd0a90ec0569a4c518835a60de5a26a13.exec.cmd: mono: not found
/home/user/.nuget/packages/ilrepack.fullauto/1.5.0/build/ILRepack.FullAuto.targets(88,5): error MSB3073: The command "mono "/home/user/.nuget/packages/ilrepack/2.0.27/tools/ILRepack.exe" --parallel --union  --internalize   --allowduplicateresources  --lib:"[cut for brevity]"" exited with code 127. [/home/user/git/Example.csproj]
```

Adding `<ILRepackBuildToolingRuntimeName>dotnet </ILRepackBuildToolingRuntimeName>` to a PropertyGroup in the csproj fixes the problem. Looks like the logic [here](https://github.com/kekyo/ILRepack.FullAuto/blob/4a205cb49b17ddb4d64fd9a336dda0b487af52e0/ILRepack.FullAuto/build/ILRepack.FullAuto.props#L42) assumes that if we are not on Windows, we should use mono. I do not agree.

**Comment by kekyo** [comment]
Modified script in 1.6.0 : https://github.com/kekyo/ILRepack.FullAuto/blob/806f0541bceec68c432a9fc41c4f455c2be62bdd/ILRepack.FullAuto/build/ILRepack.FullAuto.props#L36

* If used on Windows, execute direct "ilrepack.exe"
* If used on non-Windows and running MSBuild on CoreCLR, execute with dotnet CLI.
* If used on non-Windows and running MSBuild on mono (maybe xbuild), execute with mono CLI.

I know that it is not accurate to determine this at runtime when MSBuild is executed, but I believe that it is probably not a problem in many situations.

**Comment by kekyo** [comment]
Thanks, please reopen when required.
